### PR TITLE
Add metric property parameter_type

### PR DESCRIPTION
**Pull request by jessie-ross**
- Add metric property parameter_type

## How has this been tested?
- Existing tests pass except for integration - swagger will be updated shortly

### CODE REVIEW

**Comment by yanirs** [comment]
> Existing tests pass except for integration - swagger will be updated shortly

Done, and tests are passing. :heavy_check_mark: 

Can you please also update `MetricFull.fromApiData()`?

**Comment by dhurlburtusa** [comment]
@jessie-ross Would you please take a look at `models/MetricFull.ts` around line 46? There is a TODO there that is related to this change.

**Comment by jessie-ross** [comment]
> Would you please take a look at models/MetricFull.ts around line 46? There is a TODO there that is related to this change.

Good catch! I did have some thoughts about that.
I think we should derive it on the server since MetricBare doesn't include the eventParams/revenueParams. 

I will add a commit fixing this to the PR.

**Comment by jessie-ross** [comment]
It is still failing, I am going to take a look at the swagger file...

**Comment by yanirs** [comment]
> It is still failing, I am going to take a look at the swagger file...

Looks like it's the unit tests, not Swagger's fault. :slightly_smiling_face:

**Pull request merged**
