### PR TITLE
Demo: Experiments AgGrid

### PR DESCRIPTION
**Pull request by jessie-ross**
**This PR adds a demo Experiments table using AgGrid:**
- Better status sorting
- Better default sort - status then start date
- Advanced column filtering
- Using links for the experiment name, can open them in a new tab

See p1617909144001200-slack-G01BQ5WMR8Q for a demo vid.

Ultimately it makes visiting the experiments page much more useful dashboard of running experiments, so experimenters are more likely to use it. Also the lack of open experiment in a new tab was quite aggravating.

Notably it is missing the search, I want to re-add the search to the right of the nav bar at a later point.

## How has this been tested?

It actually shouldn't require that much to get it to full coverage, I think just a snapshot and unit testing the custom sort

- Manual testing with production data (locally)

### CODE REVIEW

**Comment by jessie-ross** [comment]
AgGrid is the main library in the open source grid game:
- Extremely reputable
- Been around for a long time, battle tested
- Very well maintained, massive community
- Heaps of features
- Open-source level should cover everything we need but has option to add on "enterprise" features at a price

**Review by yanirs — APPROVED** [review]
Looks good!

I'm happy with adding it under `/experiments-ag` and graduating to `/experiments` when it's fully tested and ready.

**Comment by withinboredom** [comment]
Do we want to add a banner to the top of `/experiments` saying something like: "try out the new experience [here] that allows better filtering. Leave feedback [on this issue]"?

**Comment by jessie-ross** [comment]
I was thinking of showing it to some experimenters, how about a message in #a8cexperiments:

> We are working on a new experiments grid for Abacus, with better sorting, proper linking, and column filtering, it isn't fully tested yet but feel free to [try it out](https://experiments.a8c.com/experiments-ag).

To me it is miles away from the current grid, so I have a feeling I know what they would say, but this gives experimenters a chance to use it with a warning.

**Pull request merged**
