### PR TITLE
Add fields to add Metric Assignment Modal

### PR DESCRIPTION
**Pull request by jessie-ross**
This PR adds fields to the Add MetricAssignment Modal:

Screen Shot 2020-09-02 at 2 29 07 am

- Allows you to add a new metric assignment and have it set to primary, no way to change primary otherwise, this should be good enough for now.

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- More testing to come later

### CODE REVIEW

**Comment by yanirs** [comment]
> Allows you to add a new metric assignment and have it set to primary, no way to change primary otherwise, this should be good enough for now.

We don't support changing the primary metric for non-staging experiments, so we should exclude the "make primary" field. It may also be worth changing the heading of the modal to "Add Secondary Metric" to make this more explicit.

**Comment by jessie-ross** [comment]
> We don't support changing the primary metric for non-staging experiments, so we should exclude the "make primary" field.

Nice! That makes it a lot simpler!

> It may also be worth changing the heading of the modal to "Add Secondary Metric" to make this more explicit.

I think it will be just fine not including it, if an Experimenter never knows it is an option it shouldn't be a problem.

**Comment by jessie-ross** [comment]
## Update

- Fixed the tests
- Extract test helper function `changeFieldByRole`

**Review by withinboredom — APPROVED** [review]
LGTM.

**Pull request merged**
