### PR TITLE
Let experimenters know dates are automatic

### PR DESCRIPTION
**Pull request by jessie-ross**
**This PR adds text underneath the start-date and end-date fields in the wizard to let Experimenters know that they are used for automation:**

Screen Shot 2020-12-11 at 2 15 25 am

Created this after seeing several experimenters surprised about it.

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)

### CODE REVIEW

**Comment by yanirs** [comment]
I think this can be made clearer. How about we change to something like this?

> :warning: The experiment will **start automatically** around midnight UTC on this date.
> :warning: The experiment will **end automatically** around midnight UTC on this date.

**Comment by aaronyan** [comment]
> ⚠️ The experiment will start and end automatically around midnight UTC on these dates.

I like this version a lot! Is it possible to have this text horizontally span the width of the modal? Similar to the other fields? If that's too much work to make look nice, I vote for shortened but separate text with no caution sign:

> Starts automatically on this date around midnight UTC.
> Ends automatically on this date around midnight UTC.

**Comment by jessie-ross** [comment]
**How is this looking:**

Screen Shot 2020-12-15 at 2 38 53 pm

- Decided to go with an info vibe instead of warning, but I think it is still pretty strong.

- I think we eventually need to move to actual labels for our controls - not the label inline with the outline, as they are a bit hard to see so aren't involved enough in creating a visual hierarchy.

**Comment by yanirs** [comment]
The alert format looks good to me. We can also drop the `Use the UTC timezone.` help texts to make it less wordy. If we want to retain the reference to UTC around the fields, we can change the `Start date` and `End date` labels to `Start date (UTC)` and `End date (UTC)`.

I'm not too fussed if you want to keep it as it is, though.

**Comment by jessie-ross** [comment]
Latest snap:
Screen Shot 2020-12-15 at 3 39 42 pm

**Comment by jessie-ross** [comment]
Ah! Is it midnight at the start of end of these dates? I am guessing it is morning version? I think it would help to include that.

**Comment by yanirs** [comment]
> Ah! Is it midnight at the start of end of these dates? I am guessing it is morning version? I think it would help to include that.

Good point. It's at the start. Maybe we can change `around midnight UTC` to `around 00:10 UTC` to make it less ambiguous?

**Comment by jessie-ross** [comment]
Screen Shot 2020-12-15 at 4 35 51 pm

**Review by yanirs — APPROVED** [review]
LGTM, though @aaronyan might want to have another look.

**Review by aaronyan — APPROVED** [review]
Woo! Looks great to me. I really like the use of alerts throughout these PRs. 🚢

**Pull request merged**
