### PR TITLE
Add health stats in debug mode

### PR DESCRIPTION
**Pull request by jessie-ross**
**This PR adds health stats at the bottom of results in debug mode.**

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)

### CODE REVIEW

**Comment by yanirs** [comment]
Hmm... I think it'd be better to add these stats to the debug page rather than the result page, and it'd also be good to have the cover the new code with tests.

**Comment by jessie-ross** [comment]
> Hmm... I think it'd be better to add these stats to the debug page rather than the result page, and it'd also be good to have the cover the new code with tests.

I'd eventually like to remove the Debug page, I think it can all be in one page with the Advanced button behind it.

The only thing really missing is providing a table for each MetricAssignment pivoting on Strategy.

**Comment by yanirs** [comment]
Taking another look at the JSON, I think it'd be even hard for us to parse it, as it relies on variation IDs. It's also hard to judge the necessity of all the ratios without knowing where it's going. Maybe instead of showing it on the page, we can `console.log()` it?

**Comment by jessie-ross** [comment]
Yeah it is not meant to be a permanent solution, just a quick cheap way of presenting data for us now. 
I am using it when I look at and compare the A/As

**Comment by yanirs** [comment]
> Yeah it is not meant to be a permanent solution, just a quick cheap way of presenting data for us now.
> I am using it when I look at and compare the A/As

OK, if it's a temporary solution I think it's all good. Before merging, can you please add an inline comment that it's temporary?

**Review by yanirs — APPROVED** [review]

**Pull request merged**
