### PR TITLE
Clean up audience panel UI

### PR DESCRIPTION
**Pull request by jessie-ross**
This PR cleans up the Audience Panel UI.
- Uses monospace
- Visually reduces the "default" label.

After:

Screen Shot 2020-09-10 at 3 49 09 am

Before:

Screen Shot 2020-09-10 at 3 57 03 am

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)

### CODE REVIEW

**Comment by aaronyan** [comment]
LGTM! As mentioned [here](https://github.com/Automattic/abacus/pull/318#issuecomment-689873712), I think having the chip component be small and outlined would be nice. Can we also remove this left padding on the **variations** and **segments** section?

92646858-9eab9b80-f319-11ea-9e23-b9369bec9a94

**Comment by jessie-ross** [comment]
## Update

- I have fixed the padding
- I have used the outlined chip, managed to still "visually reduce" it a bit by using the disabled attribute.

**Review by aaronyan — APPROVED** [review]
LGTM! Thanks for making these adjustments, Jessie.

**Comment by aaronyan** [comment]
@jessie-ross, can you help me fix these merge conflicts that I think were introduced when I merged #318?

**Comment by jessie-ross** [comment]
> @jessie-ross, can you help me fix these merge conflicts that I think were introduced when I merged #318?

Sure!

In this case since a ".snap" is the only one conflicting we just run:
```npm run test:unit -- -- --updateSnapshot```

**Comment by aaronyan** [comment]
Thanks @jessie-ross. And sweet, TIL!

**Pull request merged**
