### PR TITLE
Add complete button

### PR DESCRIPTION
**Pull request by jessie-ross**
**This PR adds a complete button to the single experiment view.**
- Adds tooltips explaining the difference between Complete and Disable.
- Adds Enumeration (1. 2. 3.) to indicate the order that an experiment should go through.

Resolves https://github.com/Automattic/experimentation-platform/issues/785

### Staging

Screenshot 2023-05-15 at 5 57 52 pm

Screenshot 2023-05-15 at 5 58 00 pm

Screenshot 2023-05-15 at 5 58 07 pm

### Running

Screenshot 2023-05-15 at 5 58 20 pm

Screenshot 2023-05-15 at 5 58 26 pm

### The new complete modal

Screenshot 2023-05-15 at 6 00 27 pm

### Completed
Screenshot 2023-05-15 at 6 00 42 pm
Screenshot 2023-05-15 at 6 00 47 pm
Screenshot 2023-05-15 at 6 00 53 pm

### Disabled
Screenshot 2023-05-15 at 6 01 08 pm
Screenshot 2023-05-15 at 6 01 13 pm
Screenshot 2023-05-15 at 6 01 20 pm

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)

### CODE REVIEW

**Comment by aaronyan** [comment]
Love the tooltips and enumeration! What do you think about putting the enumeration inside the button (ie. `1. Launch`)?

> Stop assigning new users, but users that are already assigned will continue with their assignment

What do you think of this hint? 

- "Stop new user assignments. Current assignments remain active."

**Comment by aaronyan** [comment]
What do you think about combining the three experiment control buttons into a dropdown? It would help reduce the button bloat and remove the need for the enumeration. Related issue: https://github.com/Automattic/abacus/issues/738

We could have the dropdown auto-default to the next stage of the experiment with this [split button](https://mui.com/material-ui/react-button-group/#split-button).

**Comment by jessie-ross** [comment]
Screenshot 2023-05-16 at 4 09 12 pm

Great idea putting the numbers inside the buttons 😄

**Comment by jessie-ross** [comment]
>  "Stop new user assignments. Current assignments remain active."

I've changed the hint to match this

**Review by razvanpapadopol — APPROVED** [review]
LGTM, including the new unit tests 🚀 
Design-wise, the numbered buttons and the tooltips are awesome!

**Review by aaronyan — APPROVED** [review]
LGTM. Thanks for adding this!

**Pull request merged**
