### PR TITLE
Experiment overview: allow p2 url editing in any status

### PR DESCRIPTION
**Pull request by razvanpapadopol**
Fixes https://github.com/Automattic/abacus/issues/609

- Added a new field to the edit experiment modal for non-staging experiments to update the P2 URL.
- Add unit test coverage.

Screenshot 2023-05-19 at 20 56 58

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- Manual testing with mock data (locally or on Vercel)
- Additional manual testing instructions (please specify):
  * <s>Apply D11131-code</s> (API changes were deployed)
  * Open a non-staging experiment and edit its details

### CODE REVIEW

**Review by aaronyan — APPROVED** [review]
LGTM. Thanks for the fast PR on this, Razvan! Probably best to let Jessie give a final review on this before merging

**Comment by jessie-ross** [comment]
It looks like this PR is supposed to have https://github.com/Automattic/abacus/pull/873 as a base

**Comment by jessie-ross** [comment]
I'm not too sure what has changed here, I might review this one after it's been rebased

**Comment by razvanpapadopol** [comment]
> It looks like this PR is supposed to have https://github.com/Automattic/abacus/pull/873 as a base

Yes, that's right! Forgot to select the correct "base" branch but I'll rebase after merging https://github.com/Automattic/abacus/pull/873

**Review by jessie-ross — APPROVED** [review]
Nice small addition, looks good to me 🚀

**Pull request merged**
