### PR TITLE
CRA Part 2: The big restructure

### PR DESCRIPTION
**Pull request by jessie-ross**
**NOTE: We should merges this series of PRs together.**

**This PR is the second of three migrating this app from NextJS to CRA, this one restructures our files.**
- CRA supports absolute imports but not path aliasing (the import from `@/...` part)
- This PR _only_ moves source files to `/src` and changes imports from `@/` to `src/` and updates 3 config files
- Using `src/` references is functionally the same as using `@/`
- Unfortunately the imports are sorted together by eslint :/

Part of a series on #212, the last one should be quite reasonable.

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)

### CODE REVIEW

**Comment by jessie-ross** [comment]
The integration tests should pass but it looks like swagger is timing out, likely just from rate limiting so should be good to retry  in a bit.

**Review by withinboredom — COMMENTED** [review]
Did we mean to include `.DS_Store`?

**Comment by jessie-ross** [comment]
> Did we mean to include .DS_Store?

Nope!

**Comment by jessie-ross** [comment]
This is no longer needed thanks to #364

**Pull request closed without merging**
