### PR TITLE
Experiment top level button UI

### PR DESCRIPTION
**Pull request by jessie-ross**
**This PR adds just the UI for top level buttons:**

Screen Shot 2020-09-03 at 2 09 02 am

Coming later:
- Disable Confirm dialog
- Edit in Wizard
- Every button's disable state and tooltips.

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)

### CODE REVIEW

**Comment by jessie-ross** [comment]
I prefer the outlined buttons but this is what it looks like with contained buttons:

Screen Shot 2020-09-03 at 2 08 27 am


And disabled contained buttons:

Screen Shot 2020-09-03 at 2 06 41 am

**Comment by aaronyan** [comment]
Looking good so far. I also prefer the outlined buttons! :) 

I think we will also want to show a `Start` button as a top level button (disabled for non-staging experiments).

**Comment by jessie-ross** [comment]
I've decided to go with "Run" instead of "Start" since it matches our state of "running".

**Here is what it looks likes for different statuses:** 

`staging`

Screen Shot 2020-09-03 at 11 50 58 pm

`running` and `completed`

Screen Shot 2020-09-03 at 11 50 30 pm

`disabled`

Screen Shot 2020-09-03 at 11 50 14 pm

**Review by yanirs — APPROVED** [review]
LGTM

**Pull request merged**
