### PR TITLE
Improve schema for production data

### LINKED ISSUE #223: Fix validation on metric or segment assignments
Unable to load [experiment details pages](https://experiments.a8c.com/experiments/91) at the moment. This error is returned:

`ValidationError` with `message: "metricAssignments[0].experimentId must be defined"`.

Depending on the experiment, sometimes this message also appears:

`ValidationError` with `message: "segmentAssignments[0].experimentId must be defined"`.

Screen Shot 2020-07-20 at 5 21 12 PM

### PR DESCRIPTION
**Pull request by jessie-ross**
This PR proposes:
- Remove `experimentId` field references not in production data.
- Add testing around metric parameters

Fixes #223.

## How has this been tested?
- MT & AT

### CODE REVIEW

**Comment by jessie-ross** [comment]
One of the test metrics in the production data: `metricId = 3` is invalid:
```
{
   "metric_id":3,
   "name":"metric_name_test2",
   "description":"hello world",
   "parameter_type":"conversion",
   "higher_is_better":false,
   "event_params":{  // <-------- This should be content of `events` below
      "events":[  
         {
             ...
         }
      ]
   },
   "revenue_params":null
}
```

**Comment by jessie-ross** [comment]
Fixes #223

**Comment by yanirs** [comment]
> One of the test metrics in the production data: `metricId = 3` is invalid:
> 
> ```
> {
>    "metric_id":3,
>    "name":"metric_name_test2",
>    "description":"hello world",
>    "parameter_type":"conversion",
>    "higher_is_better":false,
>    "event_params":{  // <-------- This should be content of `events` below
>       "events":[  
>          {
>              ...
>          }
>       ]
>    },
>    "revenue_params":null
> }
> ```

Looks like it was used in the past for development. I just fixed it. Let me know if you hit other bad production data and we can either drop or fix it.

> Fixes #223

Should add this to the PR description for auto-closing. :slightly_smiling_face: See [GitHub docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by jessie-ross** [comment]
> Thanks for getting this started @jessie-ross! Testing this out on the Vercel, and I'm having trouble loading the details page and seeing segment id and deployed variation id errors.

Yeah this PR is for the production data - I didn't test it on the mock.
This isn't to do with the schema but rather the mock data in swagger being incorrect after I changing the mock data recently (by adding the segmentIds).
I've created a seperate issue for it: #226, with some comments relating to this issue.

**Comment by yanirs** [comment]
> Yeah this PR is for the production data - I didn't test it on the mock.

Let's make sure this works with both the production and mock data before we merge it. The mock is useful. :slightly_smiling_face:

**Comment by jessie-ross** [comment]
This PR should be ready to go.

**Comment by yanirs** [comment]
> This PR should be ready to go.

@jessie-ross as noted, let's address the issue @aaronyan mentioned before merging and be more specific about testing notes. From "MT & AT" I have no idea how this was tested, what was actually fixed, and why it is ready to go. I don't see how it fixes #223, and the detail page on Vercel is still broken. Can you please address the mock issue and adding testing notes so we can fully review this PR?

**Comment by jessie-ross** [comment]
Sorry I might have been a bit too brief on this PR.
I had felt that this issue was minor enough for this to pass.

> From "MT & AT" I have no idea how this was tested, what was actually fixed, and why it is ready to go. 

Sure, I will be a bit more specific next time.
I tested this using the Production server and the Mock Server.
I did thorough Manual testing on production and apparently not enough on the Mock Server.

> I don't see how it fixes #223

#223 shows errors on the Production Site, namely the missing experimentId, this PR directly fixes those errors.

> and the detail page on Vercel is still broken.

This should be independent from #223 and I created #226 because I felt it needed a bit of discussion. 
I do intend to fix #226 basically immediately but it isn't something that can be fixed in this PR as it is a change to our swagger docs. There will be a PR there shortly.

>  Can you please address the mock issue and adding testing notes so we can fully review this PR?

For testing notes:
1. Set your local abacus to point to the production server.
2. Visit /experiments and open some experiments, /metrics and open a metric

To get at Automated testing for this category of issues we would need to run tests against a "Real" server as mentioned in the discussion part of #226.

**Comment by yanirs** [comment]
Thanks for the extra details, @jessie-ross! This looks good to me and it does fix the issue locally with the production API, so let's get it merged &ndash; I agree that the issue with the mock should be addressed separately.

**Comment by aaronyan** [comment]
Thank you for creating that other issue and fixing both, @jessie-ross! And thanks for the clarify and guidance @yanirs!

**Pull request merged**
