### PR TITLE
Metrics: add toggle to show/hide archived and debug metrics

### PR DESCRIPTION
**Pull request by razvanpapadopol**
Fixes https://github.com/Automattic/experimentation-platform/issues/912

* Hide `'archived_*'` metrics by default in the Metrics Table. For metric assignments, they are already hidden.
* Add a toggle (checkbox) to the top-right, above the table to allow showing archived metrics (for documentation, reviewing old experiments, etc).
* Add another toggle to allow showing debug (test) metrics (for viewing, testing experimental metrics).
* Add test coverage for filtering out archived and debug metrics and for the show/hide toggles functionality.

Screenshot 2023-05-16 at 02 32 10

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- Additional manual testing instructions (please specify):
  * Checking the "Show archived metrics" checkbox should display also the archived metrics in the Metrics table.
  * Checking the "Show debug metrics" checkbox should display also the debug metrics in the Metrics table.
  * Search state should remain unchanged.

### CODE REVIEW

**Comment by razvanpapadopol** [comment]
@aaronyan, when testing this feature, I've noticed that 46-explat-metric is not following the naming convention because of a typo I guess. Is it ok to re-rename it?

**Comment by aaronyan** [comment]
Looks great, thanks @razvanpapadopol!

> when testing this feature, I've noticed that 46-explat-metric is not following the naming convention because of a typo I guess. Is it ok to re-rename it?

Definitely! I've renamed the metric from `archive_` to `archived_`.

**Review by jessie-ross — APPROVED** [review]
This looks good to me!
While you're there, could you also add a show debug metrics checkbox and allow the debug metrics to come through?

**Review by aaronyan — APPROVED** [review]
LGTM! Thanks for adding these changes, @razvanpapadopol.

**Review by aaronyan — APPROVED** [review]
LGTM! Thanks for adding these changes, @razvanpapadopol.

**Pull request merged**
