### PR TITLE
Use React Router (Redo): Pt 3/3: Change links to use React-Router

### PR DESCRIPTION
**Pull request by jessie-ross**
**This PR changes links to use React Router instead of NextJS.**

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- Manual testing with mock data (locally or on Vercel)

### CODE REVIEW

**Review by yanirs — APPROVED** [review]
Did some manual testing and I think the stacked PRs are good to go. :ship: I like the disappearance of some hacks! :partying_face: 

Is the complete removal of the Next.js dependency coming in a separate PR?

**Comment by aaronyan** [comment]
Tested all the links this using production APIs, and everything is working as expected! Thank you @yanirs for helping to review the React-Router PRs!

**Comment by jessie-ross** [comment]
> Is the complete removal of the Next.js dependency coming in a separate PR?

Yep almost there with it.

Thanks to the new release of CRA 4.0.0 things are a lot smoother this time, I am just dealing with a bug to do with testing.

**Comment by jessie-ross** [comment]
@withinboredom does this resolve #294?

**Pull request merged**
